services:
  octapus:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: octapus
    ports:
      - "0.0.0.0:5000:5000"
    volumes:
      - ./logs:/opt/octapusprime/bin/logs
      - ./scenarios:/opt/octapusprime/scenarios
    environment:
      - PYTHONUNBUFFERED=1
