services:
  octapus:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: octapus
    network_mode: host
    privileged: true
    cap_add:
      - NET_ADMIN
      - NET_RAW
    volumes:
      - ./logs:/opt/octapusprime/bin/logs
      - ./scenarios:/opt/octapusprime/scenarios
    environment:
      - PYTHONUNBUFFERED=1
